pipeline:
    test:
        image: node:10.14.2
        commands:
            - yarn install
            - yarn run lint
    package:
        image: node:10.14.2
        commands:
            - yarn run pack
        when:
            event: tag
    publish:
        image: plugins/npm
        folder: dist
        when:
            event: tag
